name: Generic Skip for [test-contracts]
# Handles skipped but required checks

on:
  pull_request:
    paths-ignore:
      - "packages/contracts/**"

jobs:
  test-contracts:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No tests required" '
