name: Test contracts

env:
  CI: true
  FORCE_COLOR: true

on:
  push:
    branches: ['main', 'dev']
    paths:
      - ".github/workflows/test-contracts.yml"
      - "packages/contracts/**"
  pull_request:
    branches: ['main', 'dev']
    paths:
      - ".github/workflows/test-contracts.yml"
      - "packages/contracts/**"

jobs:
  test-contracts:
    runs-on: ubuntu-latest

    # This condition checks if the pull request is not a draft
    if: github.event.pull_request.draft == false

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        env:
          FORCE_COLOR: 0
        with:
          node-version: 18.17.1
          cache: 'yarn'

      - run: yarn install --frozen-lockfile

      - name: Test contracts
        run: yarn test-contracts
        env:
          NODE_OPTIONS: --max-old-space-size=4096

  test-coverage:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.pull_request.labels.*.name, 'coverage') }}
    continue-on-error: true

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        env:
          FORCE_COLOR: 0
        with:
          node-version: 18.17.1
          cache: 'yarn'

      - run: yarn install --frozen-lockfile

      - name: Test contract coverage
        run: yarn coverage
        continue-on-error: true
        env:
          NODE_OPTIONS: --max-old-space-size=4096

      - name: Publish code coverage report
        uses: codecov/codecov-action@v3
        with:
          files: ./packages/contracts/coverage/coverage-final.json 
          flags: smart-contract-tests
